name: noelboss
favicon: null
layout_spectrum: 0.3422133850399405
typography_spectrum: 0.3782475886400789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e7e8'
    - '#010101'
    - '#d5a597'
    - '#401f10'
    - '#774046'
  brandStrength: 0.875
  lightness: 0.9965930550824851
  saturation: 0.875
  rhythmicContrast: 0.14103943319059908
purpose: []
